# Feature Engineering

This notebook converts raw candidate profiles into numerical features that can be used for candidate ranking.

In [138]:
import json
import pandas as pd
import numpy as np

In [139]:
NUM_CANDIDATES = 5000

candidates = []

with open("../data/candidates.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        candidates.append(json.loads(line))

        if len(candidates) == NUM_CANDIDATES:
            break

print(f"Loaded {len(candidates)} candidates.")

Loaded 5000 candidates.

## Feature Definitions

Each function extracts one measurable aspect of candidate suitability.

In [140]:
#function to calculate experience score
def experience_score(candidate):
    years = candidate["profile"]["years_of_experience"]

    if 5 <= years <= 9:
        return 1.0
    elif 4 <= years <= 12:
        return 0.7
    else:
        return 0.3

In [141]:
def open_to_work_score(candidate):
    return float(
        candidate["redrob_signals"]["open_to_work_flag"]
    )

In [142]:
def response_rate_score(candidate):
    return candidate["redrob_signals"][
        "recruiter_response_rate"
    ]

In [143]:
def notice_score(candidate):
    days = candidate["redrob_signals"][
        "notice_period_days"
    ]

    if days <= 30:
        return 1.0
    elif days <= 60:
        return 0.5
    else:
        return 0.0

In [144]:
def github_score(candidate):
    score = candidate["redrob_signals"][
        "github_activity_score"
    ]

    if score == -1:
        return 0

    return score / 100

In [145]:
def relocation_score(candidate):
    return float(
        candidate["redrob_signals"][
            "willing_to_relocate"
        ]
    )

In [146]:
EVIDENCE_WORDS = [
    "shipped",
    "production",
    "retrieval",
    "ranking",
    "recommendation",
    "search",
    "embedding",
    "evaluation",
    "a/b",
    "learning-to-rank",
    "offline metrics",
    "online metrics",
    "relevance"
]

In [147]:
def career_evidence_score(candidate):
    text = ""

    for job in candidate["career_history"]:
        text += (
            (job.get("title") or "")
            + " "
            + (job.get("description") or "")
            + " "
        )

    text = text.lower()

    score = 0

    for word in EVIDENCE_WORDS:
        if word in text:
            score += 1

    return score / len(EVIDENCE_WORDS)

In [148]:
KEYWORD_WEIGHTS = {
    "retrieval": 5,
    "ranking": 5,
    "recommendation": 5,
    "recommender": 5,
    "search": 4,
    "embedding": 4,
    "embeddings": 4,
    "vector": 3,
    "faiss": 5,
    "pinecone": 5,
    "milvus": 5,
    "qdrant": 5,
    "weaviate": 5,
    "elasticsearch": 4,
    "opensearch": 4,
    "semantic": 3
}

In [149]:
#Keyword score function
def keyword_relevance_score(candidate):
    text = ""

    profile = candidate["profile"]

    text += (profile.get("headline") or "") + " "
    text += (profile.get("summary") or "") + " "

    for job in candidate["career_history"]:
        text += (job.get("title") or "") + " "
        text += (job.get("description") or "") + " "

    for skill in candidate["skills"]:
        text += (skill.get("name") or "") + " "

    text = text.lower()

    score = 0

    for word, weight in KEYWORD_WEIGHTS.items():
        if word in text:
            score += weight

    return score

# Feature Engineering

This notebook converts raw candidate profiles into numerical features that can be used for candidate ranking.

In [150]:
import json
import pandas as pd
import numpy as np

In [151]:
NUM_CANDIDATES = 5000

candidates = []

with open("../data/candidates.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        candidates.append(json.loads(line))

        if len(candidates) == NUM_CANDIDATES:
            break

print(f"Loaded {len(candidates)} candidates.")

Loaded 5000 candidates.

## Feature Definitions

Each function extracts one measurable aspect of candidate suitability.

In [152]:
#function to calculate experience score
def experience_score(candidate):
    years = candidate["profile"]["years_of_experience"]

    if 5 <= years <= 9:
        return 1.0
    elif 4 <= years <= 12:
        return 0.7
    else:
        return 0.3

In [153]:
def open_to_work_score(candidate):
    return float(
        candidate["redrob_signals"]["open_to_work_flag"]
    )

In [154]:
def response_rate_score(candidate):
    return candidate["redrob_signals"][
        "recruiter_response_rate"
    ]

In [155]:
def notice_score(candidate):
    days = candidate["redrob_signals"][
        "notice_period_days"
    ]

    if days <= 30:
        return 1.0
    elif days <= 60:
        return 0.5
    else:
        return 0.0

In [156]:
def github_score(candidate):
    score = candidate["redrob_signals"][
        "github_activity_score"
    ]

    if score == -1:
        return 0

    return score / 100

In [157]:
def relocation_score(candidate):
    return float(
        candidate["redrob_signals"][
            "willing_to_relocate"
        ]
    )

In [158]:
EVIDENCE_WORDS = [
    "shipped",
    "production",
    "retrieval",
    "ranking",
    "recommendation",
    "search",
    "embedding",
    "evaluation",
    "a/b",
    "learning-to-rank",
    "offline metrics",
    "online metrics",
    "relevance"
]

In [159]:
def career_evidence_score(candidate):
    text = ""

    for job in candidate["career_history"]:
        text += (
            (job.get("title") or "")
            + " "
            + (job.get("description") or "")
            + " "
        )

    text = text.lower()

    score = 0

    for word in EVIDENCE_WORDS:
        if word in text:
            score += 1

    return score / len(EVIDENCE_WORDS)

In [160]:
KEYWORD_WEIGHTS = {
    "retrieval": 5,
    "ranking": 5,
    "recommendation": 5,
    "recommender": 5,
    "search": 4,
    "embedding": 4,
    "embeddings": 4,
    "vector": 3,
    "faiss": 5,
    "pinecone": 5,
    "milvus": 5,
    "qdrant": 5,
    "weaviate": 5,
    "elasticsearch": 4,
    "opensearch": 4,
    "semantic": 3
}

In [161]:
#Keyword score function
def keyword_relevance_score(candidate):
    text = ""

    profile = candidate["profile"]

    text += (profile.get("headline") or "") + " "
    text += (profile.get("summary") or "") + " "

    for job in candidate["career_history"]:
        text += (job.get("title") or "") + " "
        text += (job.get("description") or "") + " "

    for skill in candidate["skills"]:
        text += (skill.get("name") or "") + " "

    text = text.lower()

    score = 0

    for word, weight in KEYWORD_WEIGHTS.items():
        if word in text:
            score += weight

    return score

## DataFrame Creation

Converting everything into one clear DataFrame

In [162]:
#building the dataframe
features = []

for c in candidates:
    features.append({
        "candidate_id": c["candidate_id"],
        "experience_score":
            experience_score(c),
        "keyword_relevance_score":
            keyword_relevance_score(c),
        "career_evidence_score":
            career_evidence_score(c),
        "open_to_work_score":
            open_to_work_score(c),
        "response_rate_score":
            response_rate_score(c),
        "notice_score":
            notice_score(c),
        "github_score":
            github_score(c),
        "relocation_score":
            relocation_score(c)
    })

features_df = pd.DataFrame(features)

features_df.head()

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score
0,CAND_0000001,1.0,5,0.000000,1.0,0.34,0.5,0.092,0.0
1,CAND_0000002,0.3,4,0.153846,1.0,0.29,0.5,0.000,0.0
2,CAND_0000003,0.3,0,0.000000,0.0,0.46,0.0,0.000,0.0
3,CAND_0000004,0.3,4,0.153846,0.0,0.26,0.0,0.000,1.0
4,CAND_0000005,0.7,0,0.000000,1.0,0.37,1.0,0.000,1.0

In [163]:
features_df.describe()

,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score
count,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,0.644060,3.323200,0.079415,0.36720,0.436274,0.255800,0.101628,0.291400
std,0.301733,6.936625,0.071382,0.48209,0.214272,0.359989,0.174438,0.454453
min,0.300000,0.000000,0.000000,0.00000,0.040000,0.000000,0.000000,0.000000
25%,0.300000,0.000000,0.000000,0.00000,0.250000,0.000000,0.000000,0.000000
50%,0.700000,0.000000,0.076923,0.00000,0.430000,0.000000,0.000000,0.000000
75%,1.000000,4.000000,0.153846,1.00000,0.620000,0.500000,0.162000,1.000000
max,1.000000,49.000000,0.692308,1.00000,0.910000,1.000000,0.969000,1.000000

If the keyword score is not normalised it will end up dominationg all the other features hence normalising the keywords is one way to prevent potential trap candidates.

In [164]:
features_df["keyword_relevance_score_norm"] = (
    features_df["keyword_relevance_score"]/ features_df["keyword_relevance_score"].max())

features_df["behavior_score"] = (
    0.4 * features_df["open_to_work_score"]
    + 0.4 * features_df["response_rate_score"]
    + 0.2 * features_df["notice_score"]
)

features_df["final_score"] = (
    0.30 * features_df["career_evidence_score"]
    + 0.25 * features_df["keyword_relevance_score_norm"]
    + 0.20 * features_df["behavior_score"]
    + 0.15 * features_df["experience_score"]
    + 0.05 * features_df["github_score"]
    + 0.05 * features_df["relocation_score"]
)

## Baseline Ranking

Combine handcrafted features into a weighted baseline ranking model.

In [165]:
ranked = features_df.sort_values(
    by="final_score",
    ascending=False
)

ranked.head(20)

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score,keyword_relevance_score_norm,behavior_score,final_score
2024,CAND_0002025,1.0,49,0.461538,1.0,0.80,1.0,0.969,0.0,1.000000,0.920,0.770912
30,CAND_0000031,1.0,37,0.615385,1.0,0.91,0.5,0.326,1.0,0.755102,0.864,0.762491
1609,CAND_0001610,0.3,49,0.692308,1.0,0.57,0.0,0.400,1.0,1.000000,0.628,0.698292
4401,CAND_0004402,1.0,28,0.384615,1.0,0.83,0.5,0.000,0.0,0.571429,0.832,0.574642
2119,CAND_0002120,1.0,33,0.230769,1.0,0.72,0.5,0.504,0.0,0.673469,0.788,0.570398
1301,CAND_0001302,1.0,23,0.307692,1.0,0.80,0.5,0.305,0.0,0.469388,0.820,0.538905
1493,CAND_0001494,1.0,27,0.230769,1.0,0.30,0.0,0.534,1.0,0.551020,0.520,0.537686
665,CAND_0000666,1.0,24,0.384615,1.0,0.29,0.5,0.493,0.0,0.489796,0.616,0.535684
1929,CAND_0001930,1.0,28,0.230769,1.0,0.65,0.0,0.763,0.0,0.571429,0.660,0.532238
3056,CAND_0003057,1.0,30,0.153846,1.0,0.63,0.0,0.000,1.0,0.612245,0.652,0.529615
2335,CAND_0002336,1.0,33,0.153846,1.0,0.56,1.0,0.000,0.0,0.673469,0.824,0.529321
1055,CAND_0001056,1.0,36,0.153846,0.0,0.84,0.0,0.565,1.0,0.734694,0.336,0.525277
272,CAND_0000273,1.0,20,0.230769,1.0,0.47,0.5,0.292,1.0,0.408163,0.688,0.523472
1536,CAND_0001537,1.0,33,0.153846,1.0,0.67,0.5,0.000,0.0,0.673469,0.768,0.518121
1404,CAND_0001405,0.3,36,0.230769,1.0,0.69,0.0,0.633,1.0,0.734694,0.676,0.514754
1217,CAND_0001218,1.0,29,0.230769,1.0,0.82,0.0,0.000,0.0,0.591837,0.728,0.512790
3840,CAND_0003841,1.0,20,0.230769,1.0,0.71,1.0,0.267,0.0,0.408163,0.884,0.511422
164,CAND_0000165,1.0,25,0.153846,1.0,0.30,0.0,0.615,1.0,0.510204,0.520,0.508455
1146,CAND_0001147,0.7,33,0.153846,1.0,0.68,0.0,0.000,1.0,0.673469,0.672,0.503921
421,CAND_0000422,1.0,23,0.307692,1.0,0.79,0.0,0.000,0.0,0.469388,0.716,0.502855

In [166]:
candidate_lookup = {
    c["candidate_id"]: c
    for c in candidates
}

top20 = ranked.head(20)

for cid in top20["candidate_id"]:
    c = candidate_lookup[cid]

    print("=" * 85)
    print("ID:", cid)
    print("Title:", c["profile"]["current_title"])
    print("Company:", c["profile"]["current_company"])
    print("Experience:", c["profile"]["years_of_experience"])
    print("Summary:")
    print(c["profile"]["summary"][:300])
    print()

=====================================================================================
ID: CAND_0002025
Title: Senior AI Engineer
Company: Apple
Experience: 5.9
Summary:
Senior AI engineer with 5.9 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I designed the company's first hybrid retrieval system combining BM25 with dense vector recall, across a corpus of 30M+ candidate profiles. My day-t

=====================================================================================
ID: CAND_0000031
Title: Recommendation Systems Engineer
Company: Swiggy
Experience: 6.0
Summary:
Machine learning engineer with 6.0 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-

=====================================================================================
ID: CAND_0001610
Title: Machine Learning Engineer
Company: Dream11
Experience: 3.0
Summary:
Machine learning engineer with 5.2 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from

=====================================================================================
ID: CAND_0004402
Title: AI Research Engineer
Company: Yellow.ai
Experience: 6.0
Summary:
Data scientist / ML engineer with 6.0 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

=====================================================================================
ID: CAND_0002120
Title: ML Engineer
Company: HCL
Experience: 6.5
Summary:
Data scientist / ML engineer with 6.5 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0001302
Title: Computer Vision Engineer
Company: Paytm
Experience: 5.8
Summary:
Data scientist / ML engineer with 5.8 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

=====================================================================================
ID: CAND_0001494
Title: Data Scientist
Company: Haptik
Experience: 6.4
Summary:
Data scientist / ML engineer with 6.4 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at

=====================================================================================
ID: CAND_0000666
Title: Data Scientist
Company: PhonePe
Experience: 6.5
Summary:
Data scientist / ML engineer with 6.5 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. Most of my recent work has been on predictive modeling for customer-facing problems — churn, conversion, lifetime value. I'm

=====================================================================================
ID: CAND_0001930
Title: Senior Software Engineer (ML)
Company: Dream11
Experience: 6.9
Summary:
Data scientist / ML engineer with 6.9 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

=====================================================================================
ID: CAND_0003057
Title: Accountant
Company: Infosys
Experience: 7.8
Summary:
Accountant with 7.8+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augmen

=====================================================================================
ID: CAND_0002336
Title: Accountant
Company: Hooli
Experience: 8.7
Summary:
Accountant with 8.7+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augmen

=====================================================================================
ID: CAND_0001056
Title: Computer Vision Engineer
Company: Genpact AI
Experience: 5.1
Summary:
Data scientist / ML engineer with 5.1 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0000273
Title: ML Engineer
Company: BYJU'S
Experience: 5.8
Summary:
Data scientist / ML engineer with 5.8 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. Most of my recent work has been on predictive modeling for customer-facing problems — churn, conversion, lifetime value. I'm

=====================================================================================
ID: CAND_0001537
Title: Project Manager
Company: Stark Industries
Experience: 6.3
Summary:
Project Manager with 6.3+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can a

=====================================================================================
ID: CAND_0001405
Title: Data Scientist
Company: Infosys
Experience: 3.5
Summary:
Data scientist / ML engineer with 3.5 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0001218
Title: AI Specialist
Company: Nykaa
Experience: 6.4
Summary:
Data scientist / ML engineer with 6.4 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0003841
Title: ML Engineer
Company: Tech Mahindra
Experience: 5.0
Summary:
Data scientist / ML engineer with 5.0 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0000165
Title: AI Specialist
Company: Mad Street Den
Experience: 6.8
Summary:
Data scientist / ML engineer with 6.8 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at

=====================================================================================
ID: CAND_0001147
Title: Sales Executive
Company: Hooli
Experience: 11.8
Summary:
Sales Executive with 11.8+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can

=====================================================================================
ID: CAND_0000422
Title: AI Research Engineer
Company: Haptik
Experience: 6.3
Summary:
Data scientist / ML engineer with 6.3 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

In [167]:
ranked.head(20)

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score,keyword_relevance_score_norm,behavior_score,final_score
2024,CAND_0002025,1.0,49,0.461538,1.0,0.80,1.0,0.969,0.0,1.000000,0.920,0.770912
30,CAND_0000031,1.0,37,0.615385,1.0,0.91,0.5,0.326,1.0,0.755102,0.864,0.762491
1609,CAND_0001610,0.3,49,0.692308,1.0,0.57,0.0,0.400,1.0,1.000000,0.628,0.698292
4401,CAND_0004402,1.0,28,0.384615,1.0,0.83,0.5,0.000,0.0,0.571429,0.832,0.574642
2119,CAND_0002120,1.0,33,0.230769,1.0,0.72,0.5,0.504,0.0,0.673469,0.788,0.570398
1301,CAND_0001302,1.0,23,0.307692,1.0,0.80,0.5,0.305,0.0,0.469388,0.820,0.538905
1493,CAND_0001494,1.0,27,0.230769,1.0,0.30,0.0,0.534,1.0,0.551020,0.520,0.537686
665,CAND_0000666,1.0,24,0.384615,1.0,0.29,0.5,0.493,0.0,0.489796,0.616,0.535684
1929,CAND_0001930,1.0,28,0.230769,1.0,0.65,0.0,0.763,0.0,0.571429,0.660,0.532238
3056,CAND_0003057,1.0,30,0.153846,1.0,0.63,0.0,0.000,1.0,0.612245,0.652,0.529615
2335,CAND_0002336,1.0,33,0.153846,1.0,0.56,1.0,0.000,0.0,0.673469,0.824,0.529321
1055,CAND_0001056,1.0,36,0.153846,0.0,0.84,0.0,0.565,1.0,0.734694,0.336,0.525277
272,CAND_0000273,1.0,20,0.230769,1.0,0.47,0.5,0.292,1.0,0.408163,0.688,0.523472
1536,CAND_0001537,1.0,33,0.153846,1.0,0.67,0.5,0.000,0.0,0.673469,0.768,0.518121
1404,CAND_0001405,0.3,36,0.230769,1.0,0.69,0.0,0.633,1.0,0.734694,0.676,0.514754
1217,CAND_0001218,1.0,29,0.230769,1.0,0.82,0.0,0.000,0.0,0.591837,0.728,0.512790
3840,CAND_0003841,1.0,20,0.230769,1.0,0.71,1.0,0.267,0.0,0.408163,0.884,0.511422
164,CAND_0000165,1.0,25,0.153846,1.0,0.30,0.0,0.615,1.0,0.510204,0.520,0.508455
1146,CAND_0001147,0.7,33,0.153846,1.0,0.68,0.0,0.000,1.0,0.673469,0.672,0.503921
421,CAND_0000422,1.0,23,0.307692,1.0,0.79,0.0,0.000,0.0,0.469388,0.716,0.502855

As observed above the candidate we found as a genuine fit is ranked at number 2 (CAND_0000031)

Now, the only concern remaining is whether the other 19 candidates are a fit or traps

In [168]:
#inspection of the top 20 candidates
inspection_rows = []

candidate_lookup = {
    c["candidate_id"]: c
    for c in candidates
}

top20 = ranked.head(20)

for _, row in top20.iterrows():
    c = candidate_lookup[row["candidate_id"]]

    inspection_rows.append({
        "candidate_id": row["candidate_id"],
        "title": c["profile"]["current_title"],
        "company": c["profile"]["current_company"],
        "experience": c["profile"]["years_of_experience"],
        "final_score": round(row["final_score"], 3),
        "career_score": round(row["career_evidence_score"], 3),
        "keyword_relevance_score": row["keyword_relevance_score"],
        "open_to_work": c["redrob_signals"]["open_to_work_flag"]
    })

inspection_df = pd.DataFrame(inspection_rows)

inspection_df

,candidate_id,title,company,experience,final_score,career_score,keyword_relevance_score,open_to_work
0,CAND_0002025,Senior AI Engineer,Apple,5.9,0.771,0.462,49,True
1,CAND_0000031,Recommendation Systems Engineer,Swiggy,6.0,0.762,0.615,37,True
2,CAND_0001610,Machine Learning Engineer,Dream11,3.0,0.698,0.692,49,True
3,CAND_0004402,AI Research Engineer,Yellow.ai,6.0,0.575,0.385,28,True
4,CAND_0002120,ML Engineer,HCL,6.5,0.570,0.231,33,True
5,CAND_0001302,Computer Vision Engineer,Paytm,5.8,0.539,0.308,23,True
6,CAND_0001494,Data Scientist,Haptik,6.4,0.538,0.231,27,True
7,CAND_0000666,Data Scientist,PhonePe,6.5,0.536,0.385,24,True
8,CAND_0001930,Senior Software Engineer (ML),Dream11,6.9,0.532,0.231,28,True
9,CAND_0003057,Accountant,Infosys,7.8,0.530,0.154,30,True
10,CAND_0002336,Accountant,Hooli,8.7,0.529,0.154,33,True
11,CAND_0001056,Computer Vision Engineer,Genpact AI,5.1,0.525,0.154,36,False
12,CAND_0000273,ML Engineer,BYJU'S,5.8,0.523,0.231,20,True
13,CAND_0001537,Project Manager,Stark Industries,6.3,0.518,0.154,33,True
14,CAND_0001405,Data Scientist,Infosys,3.5,0.515,0.231,36,True
15,CAND_0001218,AI Specialist,Nykaa,6.4,0.513,0.231,29,True
16,CAND_0003841,ML Engineer,Tech Mahindra,5.0,0.511,0.231,20,True
17,CAND_0000165,AI Specialist,Mad Street Den,6.8,0.508,0.154,25,True
18,CAND_0001147,Sales Executive,Hooli,11.8,0.504,0.154,33,True
19,CAND_0000422,AI Research Engineer,Haptik,6.3,0.503,0.308,23,True

The next feature is to check the career alignment of the candidates as a few candidates that have titles like Sales Executive and Accountant are still in the list

In [169]:
AI_TITLES = [
    "AI Engineer",
    "Machine Learning Engineer",
    "ML Engineer",
    "Recommendation Systems Engineer",
    "Search Engineer",
    "Applied ML Engineer",
    "NLP Engineer",
    "Data Scientist",
    "AI Research Engineer",
    "MLOps Engineer",
    "Senior AI Engineer",
    "Software Engineer (ML)",
    "Backend Engineer"
]

In [170]:
def career_alignment_score(candidate):
    title = candidate["profile"]["current_title"].lower()

    positive_keywords = [
        "ai",
        "machine learning",
        "ml",
        "recommendation",
        "search",
        "nlp",
        "data scientist",
        "applied",
        "retrieval",
        "backend"
    ]

    negative_keywords = [
        "accountant",
        "sales",
        "marketing",
        "graphic",
        "content",
        "hr",
        "operations",
        "project manager",
        "business analyst",
        "customer support",
        "mechanical",
        "civil"
    ]

    if any(word in title for word in negative_keywords):
        return 0.0

    if any(word in title for word in positive_keywords):
        return 1.0

    return 0.5

In [171]:
features_df["career_alignment_score"] = [
    career_alignment_score(c)
    for c in candidates
]

In [172]:
features_df["final_score"] = (
    0.25 * features_df["career_evidence_score"]
    + 0.20 * features_df["keyword_relevance_score_norm"]
    + 0.20 * features_df["career_alignment_score"]
    + 0.15 * features_df["behavior_score"]
    + 0.10 * features_df["experience_score"]
    + 0.05 * features_df["github_score"]
    + 0.05 * features_df["relocation_score"]
)

features_df.head(20)

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score,keyword_relevance_score_norm,behavior_score,final_score,career_alignment_score
0,CAND_0000001,1.0,5,0.000000,1.0,0.34,0.5,0.092,0.0,0.102041,0.636,0.420408,1.0
1,CAND_0000002,0.3,4,0.153846,1.0,0.29,0.5,0.000,0.0,0.081633,0.616,0.177188,0.0
2,CAND_0000003,0.3,0,0.000000,0.0,0.46,0.0,0.000,0.0,0.000000,0.184,0.057600,0.0
3,CAND_0000004,0.3,4,0.153846,0.0,0.26,0.0,0.000,1.0,0.081633,0.104,0.150388,0.0
4,CAND_0000005,0.7,0,0.000000,1.0,0.37,1.0,0.000,1.0,0.000000,0.748,0.232200,0.0
5,CAND_0000006,1.0,0,0.000000,0.0,0.12,0.0,0.000,1.0,0.000000,0.048,0.157200,0.0
6,CAND_0000007,1.0,0,0.076923,0.0,0.62,1.0,0.000,1.0,0.000000,0.448,0.236431,0.0
7,CAND_0000008,0.3,0,0.000000,0.0,0.42,0.0,0.000,0.0,0.000000,0.168,0.055200,0.0
8,CAND_0000009,0.7,0,0.153846,0.0,0.53,0.0,0.000,0.0,0.000000,0.212,0.140262,0.0
9,CAND_0000010,0.7,8,0.076923,0.0,0.40,0.0,0.337,0.0,0.163265,0.160,0.262734,0.5
10,CAND_0000011,0.3,5,0.076923,0.0,0.56,0.0,0.323,0.0,0.102041,0.224,0.219389,0.5
11,CAND_0000012,0.3,0,0.000000,0.0,0.16,0.5,0.000,0.0,0.000000,0.164,0.054600,0.0
12,CAND_0000013,0.3,0,0.000000,1.0,0.28,1.0,0.356,0.0,0.000000,0.712,0.154600,0.0
13,CAND_0000014,1.0,13,0.076923,0.0,0.80,0.0,0.000,0.0,0.265306,0.320,0.320292,0.5
14,CAND_0000015,1.0,5,0.076923,1.0,0.32,0.0,0.000,0.0,0.102041,0.528,0.318839,0.5
15,CAND_0000016,1.0,0,0.153846,1.0,0.64,0.5,0.429,0.0,0.000000,0.756,0.273312,0.0
16,CAND_0000017,0.3,0,0.153846,0.0,0.27,0.0,0.000,0.0,0.000000,0.108,0.084662,0.0
17,CAND_0000018,1.0,0,0.076923,0.0,0.16,0.0,0.000,0.0,0.000000,0.064,0.228831,0.5
18,CAND_0000019,1.0,0,0.076923,0.0,0.34,0.5,0.000,0.0,0.000000,0.236,0.154631,0.0
19,CAND_0000020,1.0,4,0.153846,0.0,0.55,1.0,0.000,0.0,0.081633,0.420,0.217788,0.0

# Conclusions

- The handcrafted feature pipeline successfully prioritizes AI candidates over keyword-stuffed profiles.
- This serves as the baseline ranking model.

# Feature Engineering

This notebook converts raw candidate profiles into numerical features that can be used for candidate ranking.

In [173]:
import json
import pandas as pd
import numpy as np

In [174]:
NUM_CANDIDATES = 5000

candidates = []

with open("../data/candidates.jsonl", "r", encoding="utf-8") as f:
    for line in f:
        candidates.append(json.loads(line))

        if len(candidates) == NUM_CANDIDATES:
            break

print(f"Loaded {len(candidates)} candidates.")

Loaded 5000 candidates.

## Feature Definitions

Each function extracts one measurable aspect of candidate suitability.

In [175]:
#function to calculate experience score
def experience_score(candidate):
    years = candidate["profile"]["years_of_experience"]

    if 5 <= years <= 9:
        return 1.0
    elif 4 <= years <= 12:
        return 0.7
    else:
        return 0.3

In [176]:
def open_to_work_score(candidate):
    return float(
        candidate["redrob_signals"]["open_to_work_flag"]
    )

In [177]:
def response_rate_score(candidate):
    return candidate["redrob_signals"][
        "recruiter_response_rate"
    ]

In [178]:
def notice_score(candidate):
    days = candidate["redrob_signals"][
        "notice_period_days"
    ]

    if days <= 30:
        return 1.0
    elif days <= 60:
        return 0.5
    else:
        return 0.0

In [179]:
def github_score(candidate):
    score = candidate["redrob_signals"][
        "github_activity_score"
    ]

    if score == -1:
        return 0

    return score / 100

In [180]:
def relocation_score(candidate):
    return float(
        candidate["redrob_signals"][
            "willing_to_relocate"
        ]
    )

In [181]:
EVIDENCE_WORDS = [
    "shipped",
    "production",
    "retrieval",
    "ranking",
    "recommendation",
    "search",
    "embedding",
    "evaluation",
    "a/b",
    "learning-to-rank",
    "offline metrics",
    "online metrics",
    "relevance"
]

In [182]:
def career_evidence_score(candidate):
    text = ""

    for job in candidate["career_history"]:
        text += (
            (job.get("title") or "")
            + " "
            + (job.get("description") or "")
            + " "
        )

    text = text.lower()

    score = 0

    for word in EVIDENCE_WORDS:
        if word in text:
            score += 1

    return score / len(EVIDENCE_WORDS)

In [183]:
KEYWORD_WEIGHTS = {
    "retrieval": 5,
    "ranking": 5,
    "recommendation": 5,
    "recommender": 5,
    "search": 4,
    "embedding": 4,
    "embeddings": 4,
    "vector": 3,
    "faiss": 5,
    "pinecone": 5,
    "milvus": 5,
    "qdrant": 5,
    "weaviate": 5,
    "elasticsearch": 4,
    "opensearch": 4,
    "semantic": 3
}

In [184]:
#Keyword score function
def keyword_relevance_score(candidate):
    text = ""

    profile = candidate["profile"]

    text += (profile.get("headline") or "") + " "
    text += (profile.get("summary") or "") + " "

    for job in candidate["career_history"]:
        text += (job.get("title") or "") + " "
        text += (job.get("description") or "") + " "

    for skill in candidate["skills"]:
        text += (skill.get("name") or "") + " "

    text = text.lower()

    score = 0

    for word, weight in KEYWORD_WEIGHTS.items():
        if word in text:
            score += weight

    return score

## DataFrame Creation

Converting everything into one clear DataFrame

In [185]:
#building the dataframe
features = []

for c in candidates:
    features.append({
        "candidate_id": c["candidate_id"],
        "experience_score":
            experience_score(c),
        "keyword_relevance_score":
            keyword_relevance_score(c),
        "career_evidence_score":
            career_evidence_score(c),
        "open_to_work_score":
            open_to_work_score(c),
        "response_rate_score":
            response_rate_score(c),
        "notice_score":
            notice_score(c),
        "github_score":
            github_score(c),
        "relocation_score":
            relocation_score(c)
    })

features_df = pd.DataFrame(features)

features_df.head()

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score
0,CAND_0000001,1.0,5,0.000000,1.0,0.34,0.5,0.092,0.0
1,CAND_0000002,0.3,4,0.153846,1.0,0.29,0.5,0.000,0.0
2,CAND_0000003,0.3,0,0.000000,0.0,0.46,0.0,0.000,0.0
3,CAND_0000004,0.3,4,0.153846,0.0,0.26,0.0,0.000,1.0
4,CAND_0000005,0.7,0,0.000000,1.0,0.37,1.0,0.000,1.0

In [186]:
features_df.describe()

,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score
count,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,0.644060,3.323200,0.079415,0.36720,0.436274,0.255800,0.101628,0.291400
std,0.301733,6.936625,0.071382,0.48209,0.214272,0.359989,0.174438,0.454453
min,0.300000,0.000000,0.000000,0.00000,0.040000,0.000000,0.000000,0.000000
25%,0.300000,0.000000,0.000000,0.00000,0.250000,0.000000,0.000000,0.000000
50%,0.700000,0.000000,0.076923,0.00000,0.430000,0.000000,0.000000,0.000000
75%,1.000000,4.000000,0.153846,1.00000,0.620000,0.500000,0.162000,1.000000
max,1.000000,49.000000,0.692308,1.00000,0.910000,1.000000,0.969000,1.000000

If the keyword score is not normalised it will end up dominationg all the other features hence normalising the keywords is one way to prevent potential trap candidates.

In [187]:
features_df["keyword_score_norm"] = (
    features_df["keyword_relevance_score"]/ features_df["keyword_relevance_score"].max())

features_df["behavior_score"] = (
    0.4 * features_df["open_to_work_score"]
    + 0.4 * features_df["response_rate_score"]
    + 0.2 * features_df["notice_score"]
)

features_df["final_score"] = (
    0.30 * features_df["career_evidence_score"]
    + 0.25 * features_df["keyword_score_norm"]
    + 0.20 * features_df["behavior_score"]
    + 0.15 * features_df["experience_score"]
    + 0.05 * features_df["github_score"]
    + 0.05 * features_df["relocation_score"]
)

## Baseline Ranking

Combine handcrafted features into a weighted baseline ranking model.

In [188]:
ranked = features_df.sort_values(
    by="final_score",
    ascending=False
)

ranked.head(20)

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score,keyword_score_norm,behavior_score,final_score
2024,CAND_0002025,1.0,49,0.461538,1.0,0.80,1.0,0.969,0.0,1.000000,0.920,0.770912
30,CAND_0000031,1.0,37,0.615385,1.0,0.91,0.5,0.326,1.0,0.755102,0.864,0.762491
1609,CAND_0001610,0.3,49,0.692308,1.0,0.57,0.0,0.400,1.0,1.000000,0.628,0.698292
4401,CAND_0004402,1.0,28,0.384615,1.0,0.83,0.5,0.000,0.0,0.571429,0.832,0.574642
2119,CAND_0002120,1.0,33,0.230769,1.0,0.72,0.5,0.504,0.0,0.673469,0.788,0.570398
1301,CAND_0001302,1.0,23,0.307692,1.0,0.80,0.5,0.305,0.0,0.469388,0.820,0.538905
1493,CAND_0001494,1.0,27,0.230769,1.0,0.30,0.0,0.534,1.0,0.551020,0.520,0.537686
665,CAND_0000666,1.0,24,0.384615,1.0,0.29,0.5,0.493,0.0,0.489796,0.616,0.535684
1929,CAND_0001930,1.0,28,0.230769,1.0,0.65,0.0,0.763,0.0,0.571429,0.660,0.532238
3056,CAND_0003057,1.0,30,0.153846,1.0,0.63,0.0,0.000,1.0,0.612245,0.652,0.529615
2335,CAND_0002336,1.0,33,0.153846,1.0,0.56,1.0,0.000,0.0,0.673469,0.824,0.529321
1055,CAND_0001056,1.0,36,0.153846,0.0,0.84,0.0,0.565,1.0,0.734694,0.336,0.525277
272,CAND_0000273,1.0,20,0.230769,1.0,0.47,0.5,0.292,1.0,0.408163,0.688,0.523472
1536,CAND_0001537,1.0,33,0.153846,1.0,0.67,0.5,0.000,0.0,0.673469,0.768,0.518121
1404,CAND_0001405,0.3,36,0.230769,1.0,0.69,0.0,0.633,1.0,0.734694,0.676,0.514754
1217,CAND_0001218,1.0,29,0.230769,1.0,0.82,0.0,0.000,0.0,0.591837,0.728,0.512790
3840,CAND_0003841,1.0,20,0.230769,1.0,0.71,1.0,0.267,0.0,0.408163,0.884,0.511422
164,CAND_0000165,1.0,25,0.153846,1.0,0.30,0.0,0.615,1.0,0.510204,0.520,0.508455
1146,CAND_0001147,0.7,33,0.153846,1.0,0.68,0.0,0.000,1.0,0.673469,0.672,0.503921
421,CAND_0000422,1.0,23,0.307692,1.0,0.79,0.0,0.000,0.0,0.469388,0.716,0.502855

In [189]:
candidate_lookup = {
    c["candidate_id"]: c
    for c in candidates
}

top20 = ranked.head(20)

for cid in top20["candidate_id"]:
    c = candidate_lookup[cid]

    print("=" * 85)
    print("ID:", cid)
    print("Title:", c["profile"]["current_title"])
    print("Company:", c["profile"]["current_company"])
    print("Experience:", c["profile"]["years_of_experience"])
    print("Summary:")
    print(c["profile"]["summary"][:300])
    print()

=====================================================================================
ID: CAND_0002025
Title: Senior AI Engineer
Company: Apple
Experience: 5.9
Summary:
Senior AI engineer with 5.9 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I designed the company's first hybrid retrieval system combining BM25 with dense vector recall, across a corpus of 30M+ candidate profiles. My day-t

=====================================================================================
ID: CAND_0000031
Title: Recommendation Systems Engineer
Company: Swiggy
Experience: 6.0
Summary:
Machine learning engineer with 6.0 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-

=====================================================================================
ID: CAND_0001610
Title: Machine Learning Engineer
Company: Dream11
Experience: 3.0
Summary:
Machine learning engineer with 5.2 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from

=====================================================================================
ID: CAND_0004402
Title: AI Research Engineer
Company: Yellow.ai
Experience: 6.0
Summary:
Data scientist / ML engineer with 6.0 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

=====================================================================================
ID: CAND_0002120
Title: ML Engineer
Company: HCL
Experience: 6.5
Summary:
Data scientist / ML engineer with 6.5 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0001302
Title: Computer Vision Engineer
Company: Paytm
Experience: 5.8
Summary:
Data scientist / ML engineer with 5.8 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

=====================================================================================
ID: CAND_0001494
Title: Data Scientist
Company: Haptik
Experience: 6.4
Summary:
Data scientist / ML engineer with 6.4 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at

=====================================================================================
ID: CAND_0000666
Title: Data Scientist
Company: PhonePe
Experience: 6.5
Summary:
Data scientist / ML engineer with 6.5 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. Most of my recent work has been on predictive modeling for customer-facing problems — churn, conversion, lifetime value. I'm

=====================================================================================
ID: CAND_0001930
Title: Senior Software Engineer (ML)
Company: Dream11
Experience: 6.9
Summary:
Data scientist / ML engineer with 6.9 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

=====================================================================================
ID: CAND_0003057
Title: Accountant
Company: Infosys
Experience: 7.8
Summary:
Accountant with 7.8+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augmen

=====================================================================================
ID: CAND_0002336
Title: Accountant
Company: Hooli
Experience: 8.7
Summary:
Accountant with 8.7+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augmen

=====================================================================================
ID: CAND_0001056
Title: Computer Vision Engineer
Company: Genpact AI
Experience: 5.1
Summary:
Data scientist / ML engineer with 5.1 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0000273
Title: ML Engineer
Company: BYJU'S
Experience: 5.8
Summary:
Data scientist / ML engineer with 5.8 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. Most of my recent work has been on predictive modeling for customer-facing problems — churn, conversion, lifetime value. I'm

=====================================================================================
ID: CAND_0001537
Title: Project Manager
Company: Stark Industries
Experience: 6.3
Summary:
Project Manager with 6.3+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can a

=====================================================================================
ID: CAND_0001405
Title: Data Scientist
Company: Infosys
Experience: 3.5
Summary:
Data scientist / ML engineer with 3.5 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0001218
Title: AI Specialist
Company: Nykaa
Experience: 6.4
Summary:
Data scientist / ML engineer with 6.4 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0003841
Title: ML Engineer
Company: Tech Mahindra
Experience: 5.0
Summary:
Data scientist / ML engineer with 5.0 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0000165
Title: AI Specialist
Company: Mad Street Den
Experience: 6.8
Summary:
Data scientist / ML engineer with 6.8 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at

=====================================================================================
ID: CAND_0001147
Title: Sales Executive
Company: Hooli
Experience: 11.8
Summary:
Sales Executive with 11.8+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can

=====================================================================================
ID: CAND_0000422
Title: AI Research Engineer
Company: Haptik
Experience: 6.3
Summary:
Data scientist / ML engineer with 6.3 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

In [190]:
ranked.head(20)

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score,keyword_score_norm,behavior_score,final_score
2024,CAND_0002025,1.0,49,0.461538,1.0,0.80,1.0,0.969,0.0,1.000000,0.920,0.770912
30,CAND_0000031,1.0,37,0.615385,1.0,0.91,0.5,0.326,1.0,0.755102,0.864,0.762491
1609,CAND_0001610,0.3,49,0.692308,1.0,0.57,0.0,0.400,1.0,1.000000,0.628,0.698292
4401,CAND_0004402,1.0,28,0.384615,1.0,0.83,0.5,0.000,0.0,0.571429,0.832,0.574642
2119,CAND_0002120,1.0,33,0.230769,1.0,0.72,0.5,0.504,0.0,0.673469,0.788,0.570398
1301,CAND_0001302,1.0,23,0.307692,1.0,0.80,0.5,0.305,0.0,0.469388,0.820,0.538905
1493,CAND_0001494,1.0,27,0.230769,1.0,0.30,0.0,0.534,1.0,0.551020,0.520,0.537686
665,CAND_0000666,1.0,24,0.384615,1.0,0.29,0.5,0.493,0.0,0.489796,0.616,0.535684
1929,CAND_0001930,1.0,28,0.230769,1.0,0.65,0.0,0.763,0.0,0.571429,0.660,0.532238
3056,CAND_0003057,1.0,30,0.153846,1.0,0.63,0.0,0.000,1.0,0.612245,0.652,0.529615
2335,CAND_0002336,1.0,33,0.153846,1.0,0.56,1.0,0.000,0.0,0.673469,0.824,0.529321
1055,CAND_0001056,1.0,36,0.153846,0.0,0.84,0.0,0.565,1.0,0.734694,0.336,0.525277
272,CAND_0000273,1.0,20,0.230769,1.0,0.47,0.5,0.292,1.0,0.408163,0.688,0.523472
1536,CAND_0001537,1.0,33,0.153846,1.0,0.67,0.5,0.000,0.0,0.673469,0.768,0.518121
1404,CAND_0001405,0.3,36,0.230769,1.0,0.69,0.0,0.633,1.0,0.734694,0.676,0.514754
1217,CAND_0001218,1.0,29,0.230769,1.0,0.82,0.0,0.000,0.0,0.591837,0.728,0.512790
3840,CAND_0003841,1.0,20,0.230769,1.0,0.71,1.0,0.267,0.0,0.408163,0.884,0.511422
164,CAND_0000165,1.0,25,0.153846,1.0,0.30,0.0,0.615,1.0,0.510204,0.520,0.508455
1146,CAND_0001147,0.7,33,0.153846,1.0,0.68,0.0,0.000,1.0,0.673469,0.672,0.503921
421,CAND_0000422,1.0,23,0.307692,1.0,0.79,0.0,0.000,0.0,0.469388,0.716,0.502855

As observed above the candidate we found as a genuine fit is ranked at number 2 (CAND_0000031)

Now, the only concern remaining is whether the other 19 candidates are a fit or traps

In [191]:
#inspection of the top 20 candidates
inspection_rows = []

candidate_lookup = {
    c["candidate_id"]: c
    for c in candidates
}

top20 = ranked.head(20)

for _, row in top20.iterrows():
    c = candidate_lookup[row["candidate_id"]]

    inspection_rows.append({
        "candidate_id": row["candidate_id"],
        "title": c["profile"]["current_title"],
        "company": c["profile"]["current_company"],
        "experience": c["profile"]["years_of_experience"],
        "final_score": round(row["final_score"], 3),
        "career_score": round(row["career_evidence_score"], 3),
        "keyword_relevance_score": row["keyword_relevance_score"],
        "open_to_work": c["redrob_signals"]["open_to_work_flag"]
    })

inspection_df = pd.DataFrame(inspection_rows)

inspection_df

,candidate_id,title,company,experience,final_score,career_score,keyword_relevance_score,open_to_work
0,CAND_0002025,Senior AI Engineer,Apple,5.9,0.771,0.462,49,True
1,CAND_0000031,Recommendation Systems Engineer,Swiggy,6.0,0.762,0.615,37,True
2,CAND_0001610,Machine Learning Engineer,Dream11,3.0,0.698,0.692,49,True
3,CAND_0004402,AI Research Engineer,Yellow.ai,6.0,0.575,0.385,28,True
4,CAND_0002120,ML Engineer,HCL,6.5,0.570,0.231,33,True
5,CAND_0001302,Computer Vision Engineer,Paytm,5.8,0.539,0.308,23,True
6,CAND_0001494,Data Scientist,Haptik,6.4,0.538,0.231,27,True
7,CAND_0000666,Data Scientist,PhonePe,6.5,0.536,0.385,24,True
8,CAND_0001930,Senior Software Engineer (ML),Dream11,6.9,0.532,0.231,28,True
9,CAND_0003057,Accountant,Infosys,7.8,0.530,0.154,30,True
10,CAND_0002336,Accountant,Hooli,8.7,0.529,0.154,33,True
11,CAND_0001056,Computer Vision Engineer,Genpact AI,5.1,0.525,0.154,36,False
12,CAND_0000273,ML Engineer,BYJU'S,5.8,0.523,0.231,20,True
13,CAND_0001537,Project Manager,Stark Industries,6.3,0.518,0.154,33,True
14,CAND_0001405,Data Scientist,Infosys,3.5,0.515,0.231,36,True
15,CAND_0001218,AI Specialist,Nykaa,6.4,0.513,0.231,29,True
16,CAND_0003841,ML Engineer,Tech Mahindra,5.0,0.511,0.231,20,True
17,CAND_0000165,AI Specialist,Mad Street Den,6.8,0.508,0.154,25,True
18,CAND_0001147,Sales Executive,Hooli,11.8,0.504,0.154,33,True
19,CAND_0000422,AI Research Engineer,Haptik,6.3,0.503,0.308,23,True

The next feature is to check the career alignment of the candidates as a few candidates that have titles like Sales Executive and Accountant are still in the list

In [192]:
AI_TITLES = [
    "AI Engineer",
    "Machine Learning Engineer",
    "ML Engineer",
    "Recommendation Systems Engineer",
    "Search Engineer",
    "Applied ML Engineer",
    "NLP Engineer",
    "Data Scientist",
    "AI Research Engineer",
    "MLOps Engineer",
    "Senior AI Engineer",
    "Software Engineer (ML)",
    "Backend Engineer"
]

In [193]:
def career_alignment_score(candidate):
    title = candidate["profile"]["current_title"].lower()

    positive_keywords = [
        "ai",
        "machine learning",
        "ml",
        "recommendation",
        "search",
        "nlp",
        "data scientist",
        "applied",
        "retrieval",
        "backend"
    ]

    negative_keywords = [
        "accountant",
        "sales",
        "marketing",
        "graphic",
        "content",
        "hr",
        "operations",
        "project manager",
        "business analyst",
        "customer support",
        "mechanical",
        "civil"
    ]

    if any(word in title for word in negative_keywords):
        return 0.0

    if any(word in title for word in positive_keywords):
        return 1.0

    return 0.5

In [194]:
features_df["career_alignment_score"] = [
    career_alignment_score(c)
    for c in candidates
]

In [195]:
features_df["final_score"] = (
    0.25 * features_df["career_evidence_score"]
    + 0.20 * features_df["keyword_score_norm"]
    + 0.20 * features_df["career_alignment_score"]
    + 0.15 * features_df["behavior_score"]
    + 0.10 * features_df["experience_score"]
    + 0.05 * features_df["github_score"]
    + 0.05 * features_df["relocation_score"]
)

features_df.head(20)

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score,keyword_score_norm,behavior_score,final_score,career_alignment_score
0,CAND_0000001,1.0,5,0.000000,1.0,0.34,0.5,0.092,0.0,0.102041,0.636,0.420408,1.0
1,CAND_0000002,0.3,4,0.153846,1.0,0.29,0.5,0.000,0.0,0.081633,0.616,0.177188,0.0
2,CAND_0000003,0.3,0,0.000000,0.0,0.46,0.0,0.000,0.0,0.000000,0.184,0.057600,0.0
3,CAND_0000004,0.3,4,0.153846,0.0,0.26,0.0,0.000,1.0,0.081633,0.104,0.150388,0.0
4,CAND_0000005,0.7,0,0.000000,1.0,0.37,1.0,0.000,1.0,0.000000,0.748,0.232200,0.0
5,CAND_0000006,1.0,0,0.000000,0.0,0.12,0.0,0.000,1.0,0.000000,0.048,0.157200,0.0
6,CAND_0000007,1.0,0,0.076923,0.0,0.62,1.0,0.000,1.0,0.000000,0.448,0.236431,0.0
7,CAND_0000008,0.3,0,0.000000,0.0,0.42,0.0,0.000,0.0,0.000000,0.168,0.055200,0.0
8,CAND_0000009,0.7,0,0.153846,0.0,0.53,0.0,0.000,0.0,0.000000,0.212,0.140262,0.0
9,CAND_0000010,0.7,8,0.076923,0.0,0.40,0.0,0.337,0.0,0.163265,0.160,0.262734,0.5
10,CAND_0000011,0.3,5,0.076923,0.0,0.56,0.0,0.323,0.0,0.102041,0.224,0.219389,0.5
11,CAND_0000012,0.3,0,0.000000,0.0,0.16,0.5,0.000,0.0,0.000000,0.164,0.054600,0.0
12,CAND_0000013,0.3,0,0.000000,1.0,0.28,1.0,0.356,0.0,0.000000,0.712,0.154600,0.0
13,CAND_0000014,1.0,13,0.076923,0.0,0.80,0.0,0.000,0.0,0.265306,0.320,0.320292,0.5
14,CAND_0000015,1.0,5,0.076923,1.0,0.32,0.0,0.000,0.0,0.102041,0.528,0.318839,0.5
15,CAND_0000016,1.0,0,0.153846,1.0,0.64,0.5,0.429,0.0,0.000000,0.756,0.273312,0.0
16,CAND_0000017,0.3,0,0.153846,0.0,0.27,0.0,0.000,0.0,0.000000,0.108,0.084662,0.0
17,CAND_0000018,1.0,0,0.076923,0.0,0.16,0.0,0.000,0.0,0.000000,0.064,0.228831,0.5
18,CAND_0000019,1.0,0,0.076923,0.0,0.34,0.5,0.000,0.0,0.000000,0.236,0.154631,0.0
19,CAND_0000020,1.0,4,0.153846,0.0,0.55,1.0,0.000,0.0,0.081633,0.420,0.217788,0.0

# Conclusions

- The handcrafted feature pipeline successfully prioritizes AI candidates over keyword-stuffed profiles.
- This serves as the baseline ranking model.

## DataFrame Creation

Converting everything into one clear DataFrame

In [196]:
#building the dataframe
features = []

for c in candidates:
    features.append({
        "candidate_id": c["candidate_id"],
        "experience_score":
            experience_score(c),
        "keyword_relevance_score":
            keyword_relevance_score(c),
        "career_evidence_score":
            career_evidence_score(c),
        "open_to_work_score":
            open_to_work_score(c),
        "response_rate_score":
            response_rate_score(c),
        "notice_score":
            notice_score(c),
        "github_score":
            github_score(c),
        "relocation_score":
            relocation_score(c)
    })

features_df = pd.DataFrame(features)

features_df.head()

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score
0,CAND_0000001,1.0,5,0.000000,1.0,0.34,0.5,0.092,0.0
1,CAND_0000002,0.3,4,0.153846,1.0,0.29,0.5,0.000,0.0
2,CAND_0000003,0.3,0,0.000000,0.0,0.46,0.0,0.000,0.0
3,CAND_0000004,0.3,4,0.153846,0.0,0.26,0.0,0.000,1.0
4,CAND_0000005,0.7,0,0.000000,1.0,0.37,1.0,0.000,1.0

In [197]:
features_df.describe()

,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score
count,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000
mean,0.644060,3.323200,0.079415,0.36720,0.436274,0.255800,0.101628,0.291400
std,0.301733,6.936625,0.071382,0.48209,0.214272,0.359989,0.174438,0.454453
min,0.300000,0.000000,0.000000,0.00000,0.040000,0.000000,0.000000,0.000000
25%,0.300000,0.000000,0.000000,0.00000,0.250000,0.000000,0.000000,0.000000
50%,0.700000,0.000000,0.076923,0.00000,0.430000,0.000000,0.000000,0.000000
75%,1.000000,4.000000,0.153846,1.00000,0.620000,0.500000,0.162000,1.000000
max,1.000000,49.000000,0.692308,1.00000,0.910000,1.000000,0.969000,1.000000

If the keyword score is not normalised it will end up dominationg all the other features hence normalising the keywords is one way to prevent potential trap candidates.

In [198]:
features_df["keyword_score_norm"] = (
    features_df["keyword_relevance_score"]/ features_df["keyword_relevance_score"].max())

features_df["behavior_score"] = (
    0.4 * features_df["open_to_work_score"]
    + 0.4 * features_df["response_rate_score"]
    + 0.2 * features_df["notice_score"]
)

features_df["final_score"] = (
    0.30 * features_df["career_evidence_score"]
    + 0.25 * features_df["keyword_score_norm"]
    + 0.20 * features_df["behavior_score"]
    + 0.15 * features_df["experience_score"]
    + 0.05 * features_df["github_score"]
    + 0.05 * features_df["relocation_score"]
)

## Baseline Ranking

Combine handcrafted features into a weighted baseline ranking model.

In [199]:
ranked = features_df.sort_values(
    by="final_score",
    ascending=False
)

ranked.head(20)

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score,keyword_score_norm,behavior_score,final_score
2024,CAND_0002025,1.0,49,0.461538,1.0,0.80,1.0,0.969,0.0,1.000000,0.920,0.770912
30,CAND_0000031,1.0,37,0.615385,1.0,0.91,0.5,0.326,1.0,0.755102,0.864,0.762491
1609,CAND_0001610,0.3,49,0.692308,1.0,0.57,0.0,0.400,1.0,1.000000,0.628,0.698292
4401,CAND_0004402,1.0,28,0.384615,1.0,0.83,0.5,0.000,0.0,0.571429,0.832,0.574642
2119,CAND_0002120,1.0,33,0.230769,1.0,0.72,0.5,0.504,0.0,0.673469,0.788,0.570398
1301,CAND_0001302,1.0,23,0.307692,1.0,0.80,0.5,0.305,0.0,0.469388,0.820,0.538905
1493,CAND_0001494,1.0,27,0.230769,1.0,0.30,0.0,0.534,1.0,0.551020,0.520,0.537686
665,CAND_0000666,1.0,24,0.384615,1.0,0.29,0.5,0.493,0.0,0.489796,0.616,0.535684
1929,CAND_0001930,1.0,28,0.230769,1.0,0.65,0.0,0.763,0.0,0.571429,0.660,0.532238
3056,CAND_0003057,1.0,30,0.153846,1.0,0.63,0.0,0.000,1.0,0.612245,0.652,0.529615
2335,CAND_0002336,1.0,33,0.153846,1.0,0.56,1.0,0.000,0.0,0.673469,0.824,0.529321
1055,CAND_0001056,1.0,36,0.153846,0.0,0.84,0.0,0.565,1.0,0.734694,0.336,0.525277
272,CAND_0000273,1.0,20,0.230769,1.0,0.47,0.5,0.292,1.0,0.408163,0.688,0.523472
1536,CAND_0001537,1.0,33,0.153846,1.0,0.67,0.5,0.000,0.0,0.673469,0.768,0.518121
1404,CAND_0001405,0.3,36,0.230769,1.0,0.69,0.0,0.633,1.0,0.734694,0.676,0.514754
1217,CAND_0001218,1.0,29,0.230769,1.0,0.82,0.0,0.000,0.0,0.591837,0.728,0.512790
3840,CAND_0003841,1.0,20,0.230769,1.0,0.71,1.0,0.267,0.0,0.408163,0.884,0.511422
164,CAND_0000165,1.0,25,0.153846,1.0,0.30,0.0,0.615,1.0,0.510204,0.520,0.508455
1146,CAND_0001147,0.7,33,0.153846,1.0,0.68,0.0,0.000,1.0,0.673469,0.672,0.503921
421,CAND_0000422,1.0,23,0.307692,1.0,0.79,0.0,0.000,0.0,0.469388,0.716,0.502855

In [200]:
candidate_lookup = {
    c["candidate_id"]: c
    for c in candidates
}

top20 = ranked.head(20)

for cid in top20["candidate_id"]:
    c = candidate_lookup[cid]

    print("=" * 85)
    print("ID:", cid)
    print("Title:", c["profile"]["current_title"])
    print("Company:", c["profile"]["current_company"])
    print("Experience:", c["profile"]["years_of_experience"])
    print("Summary:")
    print(c["profile"]["summary"][:300])
    print()

=====================================================================================
ID: CAND_0002025
Title: Senior AI Engineer
Company: Apple
Experience: 5.9
Summary:
Senior AI engineer with 5.9 years of hands-on experience building production ML systems, with a focus on search, retrieval, and ranking. Most recently, I designed the company's first hybrid retrieval system combining BM25 with dense vector recall, across a corpus of 30M+ candidate profiles. My day-t

=====================================================================================
ID: CAND_0000031
Title: Recommendation Systems Engineer
Company: Swiggy
Experience: 6.0
Summary:
Machine learning engineer with 6.0 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I led the team that migrated our keyword-search-

=====================================================================================
ID: CAND_0001610
Title: Machine Learning Engineer
Company: Dream11
Experience: 3.0
Summary:
Machine learning engineer with 5.2 years of experience building ML-powered features in production. Strong background in NLP, recommendation systems, and applied AI; comfortable across the ML stack from feature engineering through deployment. Recently, I built our semantic search infrastructure from

=====================================================================================
ID: CAND_0004402
Title: AI Research Engineer
Company: Yellow.ai
Experience: 6.0
Summary:
Data scientist / ML engineer with 6.0 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

=====================================================================================
ID: CAND_0002120
Title: ML Engineer
Company: HCL
Experience: 6.5
Summary:
Data scientist / ML engineer with 6.5 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0001302
Title: Computer Vision Engineer
Company: Paytm
Experience: 5.8
Summary:
Data scientist / ML engineer with 5.8 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

=====================================================================================
ID: CAND_0001494
Title: Data Scientist
Company: Haptik
Experience: 6.4
Summary:
Data scientist / ML engineer with 6.4 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at

=====================================================================================
ID: CAND_0000666
Title: Data Scientist
Company: PhonePe
Experience: 6.5
Summary:
Data scientist / ML engineer with 6.5 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. Most of my recent work has been on predictive modeling for customer-facing problems — churn, conversion, lifetime value. I'm

=====================================================================================
ID: CAND_0001930
Title: Senior Software Engineer (ML)
Company: Dream11
Experience: 6.9
Summary:
Data scientist / ML engineer with 6.9 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

=====================================================================================
ID: CAND_0003057
Title: Accountant
Company: Infosys
Experience: 7.8
Summary:
Accountant with 7.8+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augmen

=====================================================================================
ID: CAND_0002336
Title: Accountant
Company: Hooli
Experience: 8.7
Summary:
Accountant with 8.7+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can augmen

=====================================================================================
ID: CAND_0001056
Title: Computer Vision Engineer
Company: Genpact AI
Experience: 5.1
Summary:
Data scientist / ML engineer with 5.1 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0000273
Title: ML Engineer
Company: BYJU'S
Experience: 5.8
Summary:
Data scientist / ML engineer with 5.8 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. Most of my recent work has been on predictive modeling for customer-facing problems — churn, conversion, lifetime value. I'm

=====================================================================================
ID: CAND_0001537
Title: Project Manager
Company: Stark Industries
Experience: 6.3
Summary:
Project Manager with 6.3+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can a

=====================================================================================
ID: CAND_0001405
Title: Data Scientist
Company: Infosys
Experience: 3.5
Summary:
Data scientist / ML engineer with 3.5 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0001218
Title: AI Specialist
Company: Nykaa
Experience: 6.4
Summary:
Data scientist / ML engineer with 6.4 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0003841
Title: ML Engineer
Company: Tech Mahindra
Experience: 5.0
Summary:
Data scientist / ML engineer with 5.0 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've been working on recommendation-style features but lighter on the deep-learning side — mostly classical methods like col

=====================================================================================
ID: CAND_0000165
Title: AI Specialist
Company: Mad Street Den
Experience: 6.8
Summary:
Data scientist / ML engineer with 6.8 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. I've spent the last couple of years building NLP-based classification and information extraction pipelines. I'm strongest at

=====================================================================================
ID: CAND_0001147
Title: Sales Executive
Company: Hooli
Experience: 11.8
Summary:
Sales Executive with 11.8+ years of experience driving outcomes in my domain. I have built strong functional expertise in the typical responsibilities of the role, including team management, stakeholder communication, and project delivery. Recently I've been excited about how AI and GenAI tools can

=====================================================================================
ID: CAND_0000422
Title: AI Research Engineer
Company: Haptik
Experience: 6.3
Summary:
Data scientist / ML engineer with 6.3 years of experience in applied machine learning. Worked across predictive modeling, NLP, analytics, and lightweight deployment workflows. My current role is split between dashboarding/analytics and shipping production ML models. I'm strongest at the modeling and

In [201]:
ranked.head(20)

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score,keyword_score_norm,behavior_score,final_score
2024,CAND_0002025,1.0,49,0.461538,1.0,0.80,1.0,0.969,0.0,1.000000,0.920,0.770912
30,CAND_0000031,1.0,37,0.615385,1.0,0.91,0.5,0.326,1.0,0.755102,0.864,0.762491
1609,CAND_0001610,0.3,49,0.692308,1.0,0.57,0.0,0.400,1.0,1.000000,0.628,0.698292
4401,CAND_0004402,1.0,28,0.384615,1.0,0.83,0.5,0.000,0.0,0.571429,0.832,0.574642
2119,CAND_0002120,1.0,33,0.230769,1.0,0.72,0.5,0.504,0.0,0.673469,0.788,0.570398
1301,CAND_0001302,1.0,23,0.307692,1.0,0.80,0.5,0.305,0.0,0.469388,0.820,0.538905
1493,CAND_0001494,1.0,27,0.230769,1.0,0.30,0.0,0.534,1.0,0.551020,0.520,0.537686
665,CAND_0000666,1.0,24,0.384615,1.0,0.29,0.5,0.493,0.0,0.489796,0.616,0.535684
1929,CAND_0001930,1.0,28,0.230769,1.0,0.65,0.0,0.763,0.0,0.571429,0.660,0.532238
3056,CAND_0003057,1.0,30,0.153846,1.0,0.63,0.0,0.000,1.0,0.612245,0.652,0.529615
2335,CAND_0002336,1.0,33,0.153846,1.0,0.56,1.0,0.000,0.0,0.673469,0.824,0.529321
1055,CAND_0001056,1.0,36,0.153846,0.0,0.84,0.0,0.565,1.0,0.734694,0.336,0.525277
272,CAND_0000273,1.0,20,0.230769,1.0,0.47,0.5,0.292,1.0,0.408163,0.688,0.523472
1536,CAND_0001537,1.0,33,0.153846,1.0,0.67,0.5,0.000,0.0,0.673469,0.768,0.518121
1404,CAND_0001405,0.3,36,0.230769,1.0,0.69,0.0,0.633,1.0,0.734694,0.676,0.514754
1217,CAND_0001218,1.0,29,0.230769,1.0,0.82,0.0,0.000,0.0,0.591837,0.728,0.512790
3840,CAND_0003841,1.0,20,0.230769,1.0,0.71,1.0,0.267,0.0,0.408163,0.884,0.511422
164,CAND_0000165,1.0,25,0.153846,1.0,0.30,0.0,0.615,1.0,0.510204,0.520,0.508455
1146,CAND_0001147,0.7,33,0.153846,1.0,0.68,0.0,0.000,1.0,0.673469,0.672,0.503921
421,CAND_0000422,1.0,23,0.307692,1.0,0.79,0.0,0.000,0.0,0.469388,0.716,0.502855

As observed above the candidate we found as a genuine fit is ranked at number 2 (CAND_0000031)

Now, the only concern remaining is whether the other 19 candidates are a fit or traps

In [202]:
#inspection of the top 20 candidates
inspection_rows = []

candidate_lookup = {
    c["candidate_id"]: c
    for c in candidates
}

top20 = ranked.head(20)

for _, row in top20.iterrows():
    c = candidate_lookup[row["candidate_id"]]

    inspection_rows.append({
        "candidate_id": row["candidate_id"],
        "title": c["profile"]["current_title"],
        "company": c["profile"]["current_company"],
        "experience": c["profile"]["years_of_experience"],
        "final_score": round(row["final_score"], 3),
        "career_score": round(row["career_evidence_score"], 3),
        "keyword_relevance_score": row["keyword_relevance_score"],
        "open_to_work": c["redrob_signals"]["open_to_work_flag"]
    })

inspection_df = pd.DataFrame(inspection_rows)

inspection_df

,candidate_id,title,company,experience,final_score,career_score,keyword_relevance_score,open_to_work
0,CAND_0002025,Senior AI Engineer,Apple,5.9,0.771,0.462,49,True
1,CAND_0000031,Recommendation Systems Engineer,Swiggy,6.0,0.762,0.615,37,True
2,CAND_0001610,Machine Learning Engineer,Dream11,3.0,0.698,0.692,49,True
3,CAND_0004402,AI Research Engineer,Yellow.ai,6.0,0.575,0.385,28,True
4,CAND_0002120,ML Engineer,HCL,6.5,0.570,0.231,33,True
5,CAND_0001302,Computer Vision Engineer,Paytm,5.8,0.539,0.308,23,True
6,CAND_0001494,Data Scientist,Haptik,6.4,0.538,0.231,27,True
7,CAND_0000666,Data Scientist,PhonePe,6.5,0.536,0.385,24,True
8,CAND_0001930,Senior Software Engineer (ML),Dream11,6.9,0.532,0.231,28,True
9,CAND_0003057,Accountant,Infosys,7.8,0.530,0.154,30,True
10,CAND_0002336,Accountant,Hooli,8.7,0.529,0.154,33,True
11,CAND_0001056,Computer Vision Engineer,Genpact AI,5.1,0.525,0.154,36,False
12,CAND_0000273,ML Engineer,BYJU'S,5.8,0.523,0.231,20,True
13,CAND_0001537,Project Manager,Stark Industries,6.3,0.518,0.154,33,True
14,CAND_0001405,Data Scientist,Infosys,3.5,0.515,0.231,36,True
15,CAND_0001218,AI Specialist,Nykaa,6.4,0.513,0.231,29,True
16,CAND_0003841,ML Engineer,Tech Mahindra,5.0,0.511,0.231,20,True
17,CAND_0000165,AI Specialist,Mad Street Den,6.8,0.508,0.154,25,True
18,CAND_0001147,Sales Executive,Hooli,11.8,0.504,0.154,33,True
19,CAND_0000422,AI Research Engineer,Haptik,6.3,0.503,0.308,23,True

The next feature is to check the career alignment of the candidates as a few candidates that have titles like Sales Executive and Accountant are still in the list

In [203]:
AI_TITLES = [
    "AI Engineer",
    "Machine Learning Engineer",
    "ML Engineer",
    "Recommendation Systems Engineer",
    "Search Engineer",
    "Applied ML Engineer",
    "NLP Engineer",
    "Data Scientist",
    "AI Research Engineer",
    "MLOps Engineer",
    "Senior AI Engineer",
    "Software Engineer (ML)",
    "Backend Engineer"
]

In [204]:
def career_alignment_score(candidate):
    title = candidate["profile"]["current_title"].lower()

    positive_keywords = [
        "ai",
        "machine learning",
        "ml",
        "recommendation",
        "search",
        "nlp",
        "data scientist",
        "applied",
        "retrieval",
        "backend"
    ]

    negative_keywords = [
        "accountant",
        "sales",
        "marketing",
        "graphic",
        "content",
        "hr",
        "operations",
        "project manager",
        "business analyst",
        "customer support",
        "mechanical",
        "civil"
    ]

    if any(word in title for word in negative_keywords):
        return 0.0

    if any(word in title for word in positive_keywords):
        return 1.0

    return 0.5

In [205]:
features_df["career_alignment_score"] = [
    career_alignment_score(c)
    for c in candidates
]

In [206]:
features_df["final_score"] = (
    0.25 * features_df["career_evidence_score"]
    + 0.20 * features_df["keyword_score_norm"]
    + 0.20 * features_df["career_alignment_score"]
    + 0.15 * features_df["behavior_score"]
    + 0.10 * features_df["experience_score"]
    + 0.05 * features_df["github_score"]
    + 0.05 * features_df["relocation_score"]
)

features_df.head(20)

,candidate_id,experience_score,keyword_relevance_score,career_evidence_score,open_to_work_score,response_rate_score,notice_score,github_score,relocation_score,keyword_score_norm,behavior_score,final_score,career_alignment_score
0,CAND_0000001,1.0,5,0.000000,1.0,0.34,0.5,0.092,0.0,0.102041,0.636,0.420408,1.0
1,CAND_0000002,0.3,4,0.153846,1.0,0.29,0.5,0.000,0.0,0.081633,0.616,0.177188,0.0
2,CAND_0000003,0.3,0,0.000000,0.0,0.46,0.0,0.000,0.0,0.000000,0.184,0.057600,0.0
3,CAND_0000004,0.3,4,0.153846,0.0,0.26,0.0,0.000,1.0,0.081633,0.104,0.150388,0.0
4,CAND_0000005,0.7,0,0.000000,1.0,0.37,1.0,0.000,1.0,0.000000,0.748,0.232200,0.0
5,CAND_0000006,1.0,0,0.000000,0.0,0.12,0.0,0.000,1.0,0.000000,0.048,0.157200,0.0
6,CAND_0000007,1.0,0,0.076923,0.0,0.62,1.0,0.000,1.0,0.000000,0.448,0.236431,0.0
7,CAND_0000008,0.3,0,0.000000,0.0,0.42,0.0,0.000,0.0,0.000000,0.168,0.055200,0.0
8,CAND_0000009,0.7,0,0.153846,0.0,0.53,0.0,0.000,0.0,0.000000,0.212,0.140262,0.0
9,CAND_0000010,0.7,8,0.076923,0.0,0.40,0.0,0.337,0.0,0.163265,0.160,0.262734,0.5
10,CAND_0000011,0.3,5,0.076923,0.0,0.56,0.0,0.323,0.0,0.102041,0.224,0.219389,0.5
11,CAND_0000012,0.3,0,0.000000,0.0,0.16,0.5,0.000,0.0,0.000000,0.164,0.054600,0.0
12,CAND_0000013,0.3,0,0.000000,1.0,0.28,1.0,0.356,0.0,0.000000,0.712,0.154600,0.0
13,CAND_0000014,1.0,13,0.076923,0.0,0.80,0.0,0.000,0.0,0.265306,0.320,0.320292,0.5
14,CAND_0000015,1.0,5,0.076923,1.0,0.32,0.0,0.000,0.0,0.102041,0.528,0.318839,0.5
15,CAND_0000016,1.0,0,0.153846,1.0,0.64,0.5,0.429,0.0,0.000000,0.756,0.273312,0.0
16,CAND_0000017,0.3,0,0.153846,0.0,0.27,0.0,0.000,0.0,0.000000,0.108,0.084662,0.0
17,CAND_0000018,1.0,0,0.076923,0.0,0.16,0.0,0.000,0.0,0.000000,0.064,0.228831,0.5
18,CAND_0000019,1.0,0,0.076923,0.0,0.34,0.5,0.000,0.0,0.000000,0.236,0.154631,0.0
19,CAND_0000020,1.0,4,0.153846,0.0,0.55,1.0,0.000,0.0,0.081633,0.420,0.217788,0.0

# Conclusions

- The handcrafted feature pipeline successfully prioritizes AI candidates over keyword-stuffed profiles.
- This serves as the baseline ranking model.